name: cmip6env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - panel
  - jupyter-panel-proxy
  - jupyter-server-proxy
  - xarray
  - netcdf4
  - geopandas
  - xarray 
  - numpy
  - hvplot
  - pandas
  - geoviews
  - holoviews